services:
  db:
    image: postgres:16-alpine
    container_name: quiz_postgres
    environment:
      POSTGRES_DB: quiz_db
      POSTGRES_USER: quiz_user
      POSTGRES_PASSWORD: quiz_password
    ports:
      - "5432:5432"
    volumes:
      - quiz_postgres_data:/var/lib/postgresql/data

volumes:
  quiz_postgres_data:

